export const ships = [
  'Adder',
  'Alliance Challenger',
  'Alliance Chieftain',
  'Alliance Crusader',
  'Anaconda',
  'Asp Explorer',
  'Asp Scout',
  'Beluga Liner',
  'Cobra MK IV',
  'Cobra Mk. III',
  'Diamondback Explorer',
  'Diamondback Scout',
  'Dolphin',
  'Eagle Mk. II',
  'Federal Assault Ship',
  'Federal Corvette',
  'Federal Dropship',
  'Federal Gunship',
  'Fer-de-Lance',
  'Hauler',
  'Imperial Clipper',
  'Imperial Courier',
  'Imperial Cutter',
  'Imperial Eagle',
  'Keelback',
  'Krait MkII',
  'Krait Phantom',
  'Mamba',
  'Orca',
  'Python',
  'Sidewinder Mk. I',
  'Type-10 Defender',
  'Type-6 Transporter',
  'Type-7 Transporter',
  'Type-9 Heavy',
  'Viper Mk III',
  'Viper MK IV',
  'Vulture',
];
